version: '3'

services:
  back-end:
    image: ninucco_back:latest
    container_name: ninucco_back
    ports:
      - "8080:8080"
    depends_on:
      - model
    restart: always

volumes:
  nginx-certs:
    external: true
